// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package share_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EduSchoolClassMember is the golang structure for table edu_school_class_member.
type EduSchoolClassMember struct {
	Id           int64       `json:"id"           description:"ID"`
	TeamId       int64       `json:"teamId"       description:"班级ID"`
	EmployeeId   int64       `json:"employeeId"   description:"成员ID"`
	InviteUserId int64       `json:"inviteUserId" description:"邀约人ID"`
	UnionMainId  int64       `json:"unionMainId"  description:"关联主体ID"`
	JoinAt       *gtime.Time `json:"joinAt"       description:"加入时间"`
}
