// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package share_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EduSchoolClass is the golang structure for table edu_school_class.
type EduSchoolClass struct {
	Id                int64       `json:"id"                description:"ID"`
	Name              string      `json:"name"              description:"班级名称，学校维度下唯一"`
	OwnerEmployeeId   int64       `json:"ownerEmployeeId"   description:"班主任/班长"`
	CaptainEmployeeId int64       `json:"captainEmployeeId" description:"班长/组长，仅限当前班级成员中选择"`
	UnionMainId       int64       `json:"unionMainId"       description:"所属主体单位ID"`
	ParentId          int64       `json:"parentId"          description:"父级ID"`
	Remark            string      `json:"remark"            description:"备注"`
	CreatedAt         *gtime.Time `json:"createdAt"         description:""`
	UpdatedAt         *gtime.Time `json:"updatedAt"         description:""`
	DeletedAt         *gtime.Time `json:"deletedAt"         description:""`
}
