// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduFdAccountDao = dao_interface.TIDao[internal.EduFdAccountColumns]

func NewEduFdAccount(dao ...dao_interface.IDao) EduFdAccountDao {
	return (EduFdAccountDao)(internal.NewEduFdAccountDao(dao...))
}

var (
	EduFdAccount = NewEduFdAccount()
)
