// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduSchoolTeacherDao = dao_interface.TIDao[internal.EduSchoolTeacherColumns]

func NewEduSchoolTeacher(dao ...dao_interface.IDao) EduSchoolTeacherDao {
	return (EduSchoolTeacherDao)(internal.NewEduSchoolTeacherDao(dao...))
}

var (
	EduSchoolTeacher = NewEduSchoolTeacher()
)
