// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduFdInvoiceDao = dao_interface.TIDao[internal.EduFdInvoiceColumns]

func NewEduFdInvoice(dao ...dao_interface.IDao) EduFdInvoiceDao {
	return (EduFdInvoiceDao)(internal.NewEduFdInvoiceDao(dao...))
}

var (
	EduFdInvoice = NewEduFdInvoice()
)
