// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduFdInvoiceDetailDao = dao_interface.TIDao[internal.EduFdInvoiceDetailColumns]

func NewEduFdInvoiceDetail(dao ...dao_interface.IDao) EduFdInvoiceDetailDao {
	return (EduFdInvoiceDetailDao)(internal.NewEduFdInvoiceDetailDao(dao...))
}

var (
	EduFdInvoiceDetail = NewEduFdInvoiceDetail()
)
