// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduFdBankCardDao = dao_interface.TIDao[internal.EduFdBankCardColumns]

func NewEduFdBankCard(dao ...dao_interface.IDao) EduFdBankCardDao {
	return (EduFdBankCardDao)(internal.NewEduFdBankCardDao(dao...))
}

var (
	EduFdBankCard = NewEduFdBankCard()
)
