// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduSchoolClassDao = dao_interface.TIDao[internal.EduSchoolClassColumns]

func NewEduSchoolClass(dao ...dao_interface.IDao) EduSchoolClassDao {
	return (EduSchoolClassDao)(internal.NewEduSchoolClassDao(dao...))
}

var (
	EduSchoolClass = NewEduSchoolClass()
)
