// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/edu-share/share_model/share_dao/internal"
)

type EduSchoolClassMemberDao = dao_interface.TIDao[internal.EduSchoolClassMemberColumns]

func NewEduSchoolClassMember(dao ...dao_interface.IDao) EduSchoolClassMemberDao {
	return (EduSchoolClassMemberDao)(internal.NewEduSchoolClassMemberDao(dao...))
}

var (
	EduSchoolClassMember = NewEduSchoolClassMember()
)
