// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EduSchoolClassDao is the data access object for table edu_school_class.
type EduSchoolClassDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns EduSchoolClassColumns // columns contains all the column names of Table for convenient usage.
}

// EduSchoolClassColumns defines and stores column names for table edu_school_class.
type EduSchoolClassColumns struct {
	Id                string // ID
	Name              string // 班级名称，学校维度下唯一
	OwnerEmployeeId   string // 班主任/班长
	CaptainEmployeeId string // 班长/组长，仅限当前班级成员中选择
	UnionMainId       string // 所属主体单位ID
	ParentId          string // 父级ID
	Remark            string // 备注
	CreatedAt         string //
	UpdatedAt         string //
	DeletedAt         string //
}

// eduSchoolClassColumns holds the columns for table edu_school_class.
var eduSchoolClassColumns = EduSchoolClassColumns{
	Id:                "id",
	Name:              "name",
	OwnerEmployeeId:   "owner_employee_id",
	CaptainEmployeeId: "captain_employee_id",
	UnionMainId:       "union_main_id",
	ParentId:          "parent_id",
	Remark:            "remark",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

// NewEduSchoolClassDao creates and returns a new DAO object for table data access.
func NewEduSchoolClassDao(proxy ...dao_interface.IDao) *EduSchoolClassDao {
	var dao *EduSchoolClassDao
	if len(proxy) > 0 {
		dao = &EduSchoolClassDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: eduSchoolClassColumns,
		}
		return dao
	}

	return &EduSchoolClassDao{
		group:   "default",
		table:   "edu_school_class",
		columns: eduSchoolClassColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EduSchoolClassDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EduSchoolClassDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *EduSchoolClassDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *EduSchoolClassDao) Columns() EduSchoolClassColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EduSchoolClassDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *EduSchoolClassDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EduSchoolClassDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
