// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EduFdCurrencyDao is the data access object for table edu_fd_currency.
type EduFdCurrencyDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns EduFdCurrencyColumns // columns contains all the column names of Table for convenient usage.
}

// EduFdCurrencyColumns defines and stores column names for table edu_fd_currency.
type EduFdCurrencyColumns struct {
	Code          string // 国家编码
	EnName        string // 国家英文名称
	CnName        string // 国家中文名称
	CurrencyCode  string // 货币编码
	CurrencyCn    string // 货币中文名称
	CurrencyEn    string // 货币英文名称
	Symbol        string // 货币符号
	SymbolNative  string // 货币原生符号
	IsLegalTender string // 是否法定货币：1是，0否
	CurrencyRate  string // 货币汇率，本币为人民币
}

// eduFdCurrencyColumns holds the columns for table edu_fd_currency.
var eduFdCurrencyColumns = EduFdCurrencyColumns{
	Code:          "code",
	EnName:        "en_name",
	CnName:        "cn_name",
	CurrencyCode:  "currency_code",
	CurrencyCn:    "currency_cn",
	CurrencyEn:    "currency_en",
	Symbol:        "symbol",
	SymbolNative:  "symbol_native",
	IsLegalTender: "is_legal_tender",
	CurrencyRate:  "currency_rate",
}

// NewEduFdCurrencyDao creates and returns a new DAO object for table data access.
func NewEduFdCurrencyDao(proxy ...dao_interface.IDao) *EduFdCurrencyDao {
	var dao *EduFdCurrencyDao
	if len(proxy) > 0 {
		dao = &EduFdCurrencyDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: eduFdCurrencyColumns,
		}
		return dao
	}

	return &EduFdCurrencyDao{
		group:   "default",
		table:   "edu_fd_currency",
		columns: eduFdCurrencyColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EduFdCurrencyDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EduFdCurrencyDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *EduFdCurrencyDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *EduFdCurrencyDao) Columns() EduFdCurrencyColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EduFdCurrencyDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *EduFdCurrencyDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EduFdCurrencyDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
