// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package share_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EduSchoolClassMember is the golang structure of table edu_school_class_member for DAO operations like Where/Data.
type EduSchoolClassMember struct {
	g.Meta       `orm:"table:edu_school_class_member, do:true"`
	Id           interface{} // ID
	TeamId       interface{} // 班级ID
	EmployeeId   interface{} // 成员ID
	InviteUserId interface{} // 邀约人ID
	UnionMainId  interface{} // 关联主体ID
	JoinAt       *gtime.Time // 加入时间
}
