// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package share_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EduSchoolClass is the golang structure of table edu_school_class for DAO operations like Where/Data.
type EduSchoolClass struct {
	g.Meta            `orm:"table:edu_school_class, do:true"`
	Id                interface{} // ID
	Name              interface{} // 班级名称，学校维度下唯一
	OwnerEmployeeId   interface{} // 班主任/班长
	CaptainEmployeeId interface{} // 班长/组长，仅限当前班级成员中选择
	UnionMainId       interface{} // 所属主体单位ID
	ParentId          interface{} // 父级ID
	Remark            interface{} // 备注
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	DeletedAt         *gtime.Time //
}
